targets:
  $default:
    builders:
      freezed:
        options:
          maybe_when: false
          maybe_map: false
          generic_argument_factories: true
      json_serializable:
        options:
          explicit_to_json: true
          generic_argument_factories: true
      drift_dev:
        options:
          store_date_time_values_as_text: true