name: flutter3_dart3
description: Flutter and Dart 3, clean architecture
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  retrofit: ^4.0.1
  dio: ^5.2.1+1
  json_annotation: ^4.8.1
  freezed_annotation: ^2.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  retrofit_generator: ^7.0.1
  build_runner: ^2.4.5
  json_serializable: ^6.7.0
  freezed: ^2.3.5

flutter:
  uses-material-design: true
